project:
  type: website
  output-dir: docs
#| warning: false
#| message: false
website:
  title: "Thomas Price"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Project Portfolio
        menu:
          - href: tidygas.qmd
            text: Analysis of US Gas Prices
          - href: billboard_t100.qmd
            text: Visualizing the Billboard Top 100 
          - href: Proj2.qmd
            text: Analysis of Obama and Trump's Tweets
          - href: simulation.qmd
            text: Testing GDP and Life Expectancy
          - href: Ethics_Blog.qmd
            text: Analysis of Data Ethics 
          - href: Proj5.qmd
            text: SQL Analysis of Racial Disparities in Police Searches
          - href: Thesis.qmd
            text: Using R in my Thesis Prospectus 
          - href: Presentation.qmd
            text: Examining Twitter Usage Across Presidential Administrations
        
            

format:
  html:
    theme: flatly
    toc: true
